### ISSUE TITLE
Bulk Actions: Folder Collaborations Failing

### ISSUE THREAD

**Issue by jacquesvandermerwe** [box/boxcli#168]
- [ X] I have checked that the [CLI documentation][cli-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Trying to add Folder Collaborations using the bulk mechanism with an as-user argument. The CSV file has all the containing elements but the code fails. Issuing the same command  `box folders:collaborations:add 853796XXX --login AutomationUser_XXXX@boxdevedition.com -r editor --as-user XXXX915726 ` from command line works as expected. Feedback in verbose mode:

```
 box-cli:init Initializing Box CLI +0ms
  box-cli:init Preparing for bulk input +0ms
  box-cli:init Loaded settings {
  box-cli:init   boxReportsFolderPath: '/Users/XXXX/Documents/Box-Reports',
  box-cli:init   boxReportsFileFormat: 'txt',
  box-cli:init   boxDownloadsFolderPath: '/Users/XXXX/Downloads/Box-Downloads',
  box-cli:init   outputJson: false
  box-cli:init } +4ms
  box-cli:init Using environment XXXX {
  box-cli:init   clientId: 'XXX',
  box-cli:init   enterpriseId: 'XXXX',
  box-cli:init   boxConfigFilePath: '/Users/jvandermerwe/eclipse-workspace/FileSystemCSVMetadata/config_diageotax.json',
  box-cli:init   hasInLinePrivateKey: true,
  box-cli:init   privateKeyPath: null,
  box-cli:init   name: 'DiageoTax',
  box-cli:init   defaultAsUserId: null,
  box-cli:init   useDefaultAsUser: false,
  box-cli:init   cacheTokens: true
  box-cli:init } +3ms
  box-cli:init Initialized client from environment config +5ms
  box-cli:execute Starting execution command: folders:collaborations:add argv: [
  box-cli:execute   '-r',
  box-cli:execute   'editor',
  box-cli:execute   '--bulk-file-path',
  box-cli:execute   '/Users/XXXXX/Documents/Box/Customers/XXX/FolderIndexes/content_owner_collab.csv',
  box-cli:execute   '--login',
  box-cli:execute   'AutomationUser_XXXX@boxdevedition.com',
  box-cli:execute   '--no-notify',
  box-cli:execute   '--verbose'
  box-cli:execute ] +0ms
  box-cli:execute Read bulk input file at /Users/XXXX/Documents/Box/Customers/XXXX/FolderIndexes/content_owner_collab.csv +1ms
  box-cli:execute Read 36 entries from bulk file /Users/XXXX/Documents/Box/Customers/XXXX/FolderIndexes/content_owner_collab.csv +7ms
  box-cli:execute Executing in bulk mode argv: [
  box-cli:execute   'XXX9629727',
  box-cli:execute   '--role=editor',
  box-cli:execute   '--login=AutomationUser_XXXX@boxdevedition.com',
  box-cli:execute   '--no-notify',
  box-cli:execute   '--verbose',
  box-cli:execute   '--as-user=XXXX915726'


36 entries failed!
----------
Entry 1 (
    id=XXXX9629727
    as-user=XXXX915726
) failed with error:
Error: Unexpected API Response [404 Not Found | gq0je4g6vsshjb4d.04hrs4tr06m0maebj23r411icfk] not_found - Not Found
    at Object.buildResponseError (/usr/local/lib/@box/cli/node_modules/box-node-sdk/lib/util/errors.js:120:23)
    at Object.buildUnexpectedResponseError (/usr/local/lib/@box/cli/node_modules/box-node-sdk/lib/util/errors.js:154:15)
    at /usr/local/lib/@box/cli/node_modules/box-node-sdk/lib/box-client.js:750:18
    at tryCatcher (/usr/local/lib/@box/cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/@box/cli/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/@box/cli/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/@box/cli/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/@box/cli/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/usr/local/lib/@box/cli/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/usr/local/lib/@box/cli/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/usr/local/lib/@box/cli/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/usr/local/lib/@box/cli/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/@box/cli/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/@box/cli/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/usr/local/lib/@box/cli/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._settlePromise (/usr/local/lib/@box/cli/node_modules/bluebird/js/release/promise.js:582:21)
```

### Versions Used
Box CLI: 2.4
Operating System: Mac Mojave

### Steps to Reproduce
Create a CSV file containing id,as-user as the columns and try to create bulk file entries

### Error Message, Including Stack Trace
See above in description

**Comment by mattwiller** [comment]
@jacquesvandermerwe Unfortunately, the `--as-user` flag cannot currently be set via bulk input, due to the way the command is initialized.  We already have an item on our backlog to address this issue, but just haven't gotten to it yet.  We'll update this thread when we develop a solution!

**Comment by DJLeanix** [comment]
Hi @mattwiller, how far are you with the item on the backlog? I would love to have the --as-users header to move folders of users in bulk.

**Comment by PJSimon** [comment]
@DJLeanix We'll be looking at it (SDK-1325) over the next few weeks.  Thanks for your patience!

**Comment by mattroyal** [comment]
@PJSimon , was this addressed?
