### ISSUE TITLE
Adding Display Name to a Metadata Template raises an error

### ISSUE THREAD

**Issue by jacquesvandermerwe** [box/boxcli#176]
- [X ] I have checked that the [CLI documentation][cli-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Updating an existing metadata template and trying to add a Multi Select Option but also passing in the Display Name parameter. This raises an error `Unexpected --display-name flag outside of template or field edit operation`

### Versions Used
Box CLI: 2.4
Operating System: Mac OS MOjave

### Steps to Reproduce
Issue following command
`box metadata-templates:update someInformation --multi-select Test --display-name Test  --option Opt1 -v`

### Error Message, Including Stack Trace
```
 box metadata-templates:update equinorInformation --multi-select Test --display-name Test  --option Opt1 -v
  box:@box/cli:hooks:init done +0ms
  box init version: @oclif/command@1.5.5 argv: [ 'metadata-templates:update', 'someInformation', '--multi-select', 'Test', '--display-name', 'Test', '--option', 'Opt1', '-v' ] +0ms
  box-cli:init Initializing Box CLI +0ms
  box-cli:init Loaded settings {
  box-cli:init   boxReportsFolderPath: '/Users/XXX/Documents/Box-Reports',
  box-cli:init   boxReportsFileFormat: 'txt',
  box-cli:init   boxDownloadsFolderPath: '/Users/XXX/Downloads/Box-Downloads',
  box-cli:init   outputJson: false
  box-cli:init } +1ms
  box-cli:init Using environment default {
  box-cli:init   clientId: '0XXXz',
  box-cli:init   enterpriseId: 'XXX',
  box-cli:init   boxConfigFilePath: '/Users/jvandermerwe/Downloads/box-cli/39176179_g6v3ej9f_config.json',
  box-cli:init   hasInLinePrivateKey: true,
  box-cli:init   privateKeyPath: null,
  box-cli:init   name: 'default',
  box-cli:init   defaultAsUserId: null,
  box-cli:init   useDefaultAsUser: false,
  box-cli:init   cacheTokens: true
  box-cli:init } +1ms
  box-cli:init Initialized client from environment config +3ms
  box-cli:execute Starting execution command: metadata-templates:update argv: [
  box-cli:execute   'someInformation',
  box-cli:execute   '--multi-select',
  box-cli:execute   'Test',
  box-cli:execute   '--display-name',
  box-cli:execute   'Test',
  box-cli:execute   '--option',
  box-cli:execute   'Opt1',
  box-cli:execute   '-v'
  box-cli:execute ] +0ms
  box-cli:execute Running framework error handler +0ms
  box-cli:execute Handling re-thrown error in base command handler +11ms
BoxCLIError: Unexpected --display-name flag outside of template or field edit operation
    at display-name (/usr/local/lib/@box/cli/src/commands/metadata-templates/update.js:169:10)
    at /usr/local/lib/@box/cli/src/commands/metadata-templates/update.js:249:15
    at Array.forEach (<anonymous>)
    at _parseOperations (/usr/local/lib/@box/cli/src/commands/metadata-templates/update.js:246:47)
    at MetadataTemplatesUpdateCommand.run (/usr/local/lib/@box/cli/src/commands/metadata-templates/update.js:259:20)
    at MetadataTemplatesUpdateCommand._run (/usr/local/lib/@box/cli/node_modules/@oclif/command/lib/command.js:29:31)
```

[cli-docs]: https://github.com/box/boxcli#command-topics
[api-docs]: https://developer.box.com/docs

**Comment by sujaygarlanka** [comment]
@jacquesvandermerwe Any flags to change the template must be passed first. So your command must be `box metadata-templates:update someInformation --display-name Test --multi-select Test --option Opt1 -v`. Hope this helps!
