### ISSUE TITLE
Cannot set property 'marker' of undefined after files:upload

### ISSUE THREAD

**Issue by Mic201710** [box/boxcli#194]
- [ :heavy_check_mark:] I have checked that the [CLI documentation][cli-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
I am trying to using box cli in docker container, after executing following command:
**box files:upload /test.txt -p foldeId**
 file can successfully uploaded into the folder after execution. But will get message:
**Cannot set property 'marker' of undefined**
![image](https://user-images.githubusercontent.com/25402982/81787035-0a7c2400-9533-11ea-86b7-1f1f3c1ce580.png)

`TypeError: Cannot set property 'marker' of undefined
    at PagingIterator._updatePaging (/Users/micczhang/box/boxcli-2.5.1/node_modules/box-node-sdk/lib/util/paging-iterator.js:163:38)
    at new PagingIterator (/Users/micczhang/box/boxcli-2.5.1/node_modules/box-node-sdk/lib/util/paging-iterator.js:129:8)
    at /Users/micczhang/box/boxcli-2.5.1/node_modules/box-node-sdk/lib/box-client.js:757:14
    at tryCatcher (/Users/micczhang/box/boxcli-2.5.1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/micczhang/box/boxcli-2.5.1/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/micczhang/box/boxcli-2.5.1/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/micczhang/box/boxcli-2.5.1/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/micczhang/box/boxcli-2.5.1/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/micczhang/box/boxcli-2.5.1/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/Users/micczhang/box/boxcli-2.5.1/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/Users/micczhang/box/boxcli-2.5.1/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/Users/micczhang/box/boxcli-2.5.1/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/micczhang/box/boxcli-2.5.1/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/micczhang/box/boxcli-2.5.1/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/micczhang/box/boxcli-2.5.1/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._settlePromise (/Users/micczhang/box/boxcli-2.5.1/node_modules/bluebird/js/release/promise.js:617:21)`

### Versions Used
Box CLI: @box/cli/2.5.1 linux-x64 node-v10.18.1
Operating System: Docker Container , centos 8 /Cantalina OS

### Steps to Reproduce
Issue happens in Linux/Cantalina OS:

Install Nodejs, and then download boxcli zip source code, run npm install -g
execute command:   box files:upload /test.txt -p foldeId

[cli-docs]: https://github.com/box/boxcli#command-topics
[api-docs]: https://developer.box.com/docs

**Comment by sujaygarlanka** [comment]
@Mic201710 Running the same command and not able to replicate the issue. I am running it on Mac OS Mojave though. I have not upgraded to Catalina. Is this issue a blocker for you?

**Comment by Mic201710** [comment]
@sujaygarlanka  hi, thanks for the reply. Actually I am running this command in a docker container, I am currently writing a shell script to call this command,  trying to get the execution result after this something like
`box files:upload ${localFile}  -p ${parentfolderId} `
`result=$?`
so even the file is uploaded, but the result will always be 2 as this message return back.

**Comment by Mic201710** [comment]
updated more details how reproduce the issue, please let me know if any questions.Thanks

**Comment by sujaygarlanka** [comment]
@Mic201710 I believe you are getting 2 back because when the command is being run, an error is being thrown in your environment and the exit code 2 is being returned. I would first try cloning the Github repo, running `./bin/run files:upload ${localFile} -p ${parentfolderId}` from within the boxcli folder. This will help us figure out whether the error has to do with the CLI or how you are calling the CLI commands.

**Comment by sujaygarlanka** [comment]
@Mic201710 Are you still getting this issue?

**Comment by sujaygarlanka** [comment]
We are going to close this issue. If this continues to be an issue, feel free to re-open this.
