### ISSUE TITLE
Error: SSL Error: undefined with box cli and proxy server

### ISSUE THREAD

**Issue by georg90** [box/boxcli#275]
- [ x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue

I am running into an `Error: SSL Error: undefined` error when using the `boxcli` with a proxy server.

### Steps to Reproduce

1. `npm install --global @box/cli`
2. `npm config set strict-ssl false --global`
3. `box configure:environments:add credentials.json `
4. `box configure:settings --proxy-url=REDACTED`
5.  `box configure:settings --enable-proxy`
6. `box users:get --verbose`

### Expected Behavior
API should return result

### Error Message, Including Stack Trace
```bash
[root@REDACTED box-backup]# box users:get --verbose
  box:@box/cli:hooks:init done +0ms
  box init version: @oclif/command@1.5.5 argv: [ 'users:get', '--verbose' ] +0ms
  box-cli:init Initializing Box CLI +0ms
  box-cli:init Loaded settings { boxReportsFolderPath: '/root/Documents/Box-Reports',
  box-cli:init   boxReportsFileFormat: 'txt',
  box-cli:init   boxDownloadsFolderPath: '/root/Downloads/Box-Downloads',
  box-cli:init   outputJson: false,
  box-cli:init   enableProxy: true,
  box-cli:init   proxy:
  box-cli:init    { url: 'http://REDACTED',
  box-cli:init      username: null,
  box-cli:init      password: null } } +1ms
  box-cli:init Using environment default { clientId: 'REDACTED',
  box-cli:init   enterpriseId: 'REDACTED',
  box-cli:init   boxConfigFilePath: '/root/box-backup/credentials.json',
  box-cli:init   hasInLinePrivateKey: true,
  box-cli:init   privateKeyPath: null,
  box-cli:init   name: 'default',
  box-cli:init   defaultAsUserId: null,
  box-cli:init   useDefaultAsUser: false,
  box-cli:init   cacheTokens: true } +2ms
  box-cli:init Initialized client from environment config +164ms
  box-cli:execute Starting execution command: users:get argv: [ '--verbose' ] +0ms
  box-cli:execute Running framework error handler +45ms
  box-cli:execute Handling re-thrown error in base command handler +18ms
Error: SSL Error: undefined
    at Request.onRequestResponse (/usr/local/lib/node_modules/@box/cli/node_modules/request/request.js:952:24)
    at ClientRequest.emit (events.js:198:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
    at Socket.socketOnData (_http_client.js:451:20)
    at Socket.emit (events.js:198:13)
    at Socket.Readable.read (_stream_readable.js:505:10)
    at flow (_stream_readable.js:974:34)
    at resume_ (_stream_readable.js:955:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Versions Used
Box CLI: @box/cli/3.0.0
Operating System: RHEL8

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by arjankowski** [comment]
Hi @georg90 ,

Thanks for submitting this issue, we will try to help you with it!

Can you try to execute curl command below with filled your proxy and auth token and tell us the result?

```
curl  -x < YOUR PROXY HERE in form  [protocol://]host[:port] > --location --request GET 'https://api.box.com/2.0/users/me'--header 'Authorization: Bearer < YOUR TOKEN HERE>'
```

**Comment by georg90** [comment]
I am behind a very restrictive firewall. It seems we're missing something, since squid fails with 503 and `ERR_DNS_FAIL 0`? However, I am able to ping `api.box.com` - so connection seems ok?

```bash
[root@REDACTED]# curl  -x http://PROXY:PORT--location --request GET 'https://api.box.com/2.0/users/me' --header 'Authorization: Bearer REDACTED' --verbose
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying REDACTED...
* TCP_NODELAY set
* Connected to REDACTED(REDACTED) port 3128 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to api.box.com:443
> CONNECT api.box.com:443 HTTP/1.1
> Host: api.box.com:443
> User-Agent: curl/7.61.1
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 503 Service Unavailable
< Server: squid/3.5.23
< Mime-Version: 1.0
< Date: Fri, 11 Feb 2022 13:15:35 GMT
< Content-Type: text/html;charset=utf-8
< Content-Length: 3691
< X-Squid-Error: ERR_DNS_FAIL 0
< Vary: Accept-Language
< Content-Language: en
< 
* Received HTTP code 503 from proxy after CONNECT
* CONNECT phase completed!
* Closing connection 0
curl: (56) Received HTTP code 503 from proxy after CONNECT
```

**Comment by arjankowski** [comment]
@georg90 I would say that this looks like network/firewall configuration issue. 
Can you ask your network administrator to help?
